# Generated by Django 5.0.6 on 2024-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Predictor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_name", models.CharField(max_length=255)),
                ("model_path", models.CharField(max_length=255)),
                ("labels_path", models.CharField(max_length=255)),
            ],
        ),
    ]
